name: CI

on:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
    - name: Build Svg.Maui
      run: dotnet build Svg.Maui/Svg.Maui.csproj -c Release
    - name: Build Svg.Maui.Converter
      run: dotnet build Svg.Maui.Converter/Svg.Maui.Converter.csproj -c Release
